version: '3'
services:
  mysql:
    build: ../images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_auth
    ports:
      - "3306:3306"
    volumes:
      - datavolume:/data/db
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6060:80"
    links:
      - mysql:db
volumes:
  datavolume: